name: Deploy server

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo ${{ secrets.DROPLET_PRIVATE_KEY }}
            export UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}
            export CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
            cd chat-tutorial
            cd server
            git pull
            down-compose down
            docker-compose --project-name chat up -d --build 




